const express = require("express");
const router = express.Router();
const { Warehouse, WarehouseRentBooking, WarehouseRentBill, Company } = require("../mongo");
const { userHasPermission } = require("../middleware/auth");

function canManage(req) {
  return userHasPermission(req.user, "warehouses.manage") || userHasPermission(req.user, "all");
}

function canReport(req) {
  return (
    userHasPermission(req.user, "warehouses.manage") ||
    userHasPermission(req.user, "all") ||
    userHasPermission(req.user, "report.warehouseRentLedger") ||
    userHasPermission(req.user, "report.warehouseRentMonthEnd")
  );
}

function istToday() {
  return new Date(Date.now() + 19800000).toISOString().slice(0, 10);
}

function previousMonth(month) {
  const [year, mon] = String(month).split("-").map(Number);
  const d = new Date(Date.UTC(year, (mon || 1) - 2, 1));
  return d.toISOString().slice(0, 7);
}

function currentIstMonth() {
  return new Date(Date.now() + 19800000).toISOString().slice(0, 7);
}

function billNo(rentMonth, companyId) {
  return `WRBILL-${rentMonth.replace(/-/g, "")}-${String(companyId).slice(-6)}-${Date.now()}`;
}

async function generateBillsForMonth(rentMonth, { autoGenerated = false, companyId = "" } = {}) {
  const filter = { rent_month: rentMonth, rent_flow: "receivable", billing_status: { $ne: "billed" } };
  if (companyId) filter.company_id = companyId;
  const bookings = await WarehouseRentBooking.find(filter).populate("warehouse_id", "name").populate("company_id", "name").sort({ company_id: 1, createdAt: 1 });
  const grouped = new Map();
  for (const booking of bookings) {
    if (!booking.company_id?._id) continue;
    const key = String(booking.company_id._id);
    if (!grouped.has(key)) grouped.set(key, []);
    grouped.get(key).push(booking);
  }

  const results = [];
  for (const [companyKey, rows] of grouped.entries()) {
    const companyIdObj = rows[0].company_id._id;
    let bill = await WarehouseRentBill.findOne({ company_id: companyIdObj, rent_month: rentMonth });
    const items = rows.map((row) => ({
      warehouse_id: row.warehouse_id._id,
      booking_id: row._id,
      warehouse_name: row.warehouse_id?.name || "",
      monthly_rent: Number(row.monthly_rent || 0),
    }));
    const amountToAdd = items.reduce((sum, item) => sum + Number(item.monthly_rent || 0), 0);

    if (!bill) {
      bill = await WarehouseRentBill.create({
        bill_no: billNo(rentMonth, companyIdObj),
        bill_date: istToday(),
        rent_month: rentMonth,
        company_id: companyIdObj,
        items,
        total_amount: amountToAdd,
        collected_amount: 0,
        balance_amount: amountToAdd,
        status: "pending",
        auto_generated: autoGenerated,
      });
    } else {
      const currentBookingIds = new Set((bill.items || []).map((item) => String(item.booking_id)));
      const newItems = items.filter((item) => !currentBookingIds.has(String(item.booking_id)));
      if (newItems.length) {
        bill.items.push(...newItems);
        bill.total_amount = Number(bill.total_amount || 0) + newItems.reduce((sum, item) => sum + Number(item.monthly_rent || 0), 0);
        bill.balance_amount = Math.max(Number(bill.total_amount || 0) - Number(bill.collected_amount || 0), 0);
        if (bill.balance_amount <= 0) bill.status = "collected";
        else if (Number(bill.collected_amount || 0) > 0) bill.status = "partial";
        else bill.status = "pending";
        if (autoGenerated) bill.auto_generated = true;
        await bill.save();
      }
    }

    await WarehouseRentBooking.updateMany(
      { _id: { $in: rows.map((row) => row._id) } },
      { $set: { bill_id: bill._id, billing_status: "billed" } }
    );

    results.push({
      id: String(bill._id),
      bill_no: bill.bill_no,
      company_id: companyKey,
      company_name: rows[0].company_id?.name || "",
      rent_month: bill.rent_month,
      total_amount: Number(bill.total_amount || 0),
      status: bill.status,
      item_count: bill.items?.length || 0,
      auto_generated: Boolean(bill.auto_generated),
    });
  }
  return results;
}

async function autoCreateReceivableBookingsForMonth(rentMonth) {
  const warehouses = await Warehouse.find({
    rent_flow: "receivable",
    company_id: { $ne: null },
    monthly_rent: { $gt: 0 },
  }).sort({ name: 1 });

  const existing = await WarehouseRentBooking.find({ rent_month: rentMonth }).select("warehouse_id").lean();
  const existingIds = new Set(existing.map((row) => String(row.warehouse_id)));
  const created = [];

  for (const warehouse of warehouses) {
    const warehouseId = String(warehouse._id);
    if (existingIds.has(warehouseId)) continue;
    try {
      const booking = await WarehouseRentBooking.create({
        booking_no: `WRB-${rentMonth.replace(/-/g, "")}-AUTO-${Date.now()}-${warehouseId.slice(-6)}`,
        booking_date: `${rentMonth}-01`,
        rent_month: rentMonth,
        warehouse_id: warehouse._id,
        company_id: warehouse.company_id,
        monthly_rent: Number(warehouse.monthly_rent || 0),
        rent_flow: "receivable",
        auto_booked: true,
        billing_status: "pending",
        status: "unpaid",
        paid_amount: 0,
        balance_amount: Number(warehouse.monthly_rent || 0),
        remarks: "Automatic month-end company rent booking",
      });
      existingIds.add(warehouseId);
      created.push(String(booking._id));
    } catch (error) {
      if (error?.code !== 11000) console.error(`Auto rent booking failed for warehouse ${warehouseId}:`, error.message);
    }
  }
  return created;
}

async function runWarehouseRentAutoClose() {
  try {
    const month = currentIstMonth();
    const closedMonth = previousMonth(month);
    const createdBookings = await autoCreateReceivableBookingsForMonth(closedMonth);
    const result = await generateBillsForMonth(closedMonth, { autoGenerated: true });
    if (createdBookings.length || result.length) {
      console.log(`Warehouse rent auto-close: ${createdBookings.length} booking(s), ${result.length} company bill(s) generated for ${closedMonth}`);
    }
    return result;
  } catch (error) {
    console.error("Warehouse rent auto-close failed:", error.message);
    return [];
  }
}

router.get("/", async (req, res) => {
  try {
    if (!canReport(req)) return res.status(403).json({ error: "Permission denied" });
    // Also check the previous calendar month here, so the bill is available
    // automatically even if the service was sleeping/restarted at month-end.
    await runWarehouseRentAutoClose();
    const filter = {};
    if (req.query.rent_month) filter.rent_month = String(req.query.rent_month);
    if (req.query.company_id) filter.company_id = req.query.company_id;
    if (req.query.status) filter.status = req.query.status;
    const rows = await WarehouseRentBill.find(filter)
      .populate("company_id", "name address mobile gst_no pan_no")
      .sort({ rent_month: -1, bill_date: -1, createdAt: -1 });
    return res.json(rows.map((bill) => ({
      ...bill.toObject(),
      id: String(bill._id),
      company_name: bill.company_id?.name || "",
      item_count: bill.items?.length || 0,
    })));
  } catch (error) {
    console.error(error);
    return res.status(500).json({ error: error.message });
  }
});

router.post("/generate", async (req, res) => {
  try {
    if (!canManage(req)) return res.status(403).json({ error: "Permission denied" });
    const rentMonth = String(req.body.rent_month || "").trim();
    if (!/^\d{4}-\d{2}$/.test(rentMonth)) return res.status(400).json({ error: "Valid rent month is required (YYYY-MM)" });
    const result = await generateBillsForMonth(rentMonth, { autoGenerated: false, companyId: String(req.body.company_id || "").trim() });
    return res.json({ ok: true, rent_month: rentMonth, bills: result, generated_count: result.length });
  } catch (error) {
    console.error(error);
    return res.status(500).json({ error: error.message });
  }
});

router.post("/collect/:id", async (req, res) => {
  try {
    if (!canManage(req)) return res.status(403).json({ error: "Permission denied" });
    const amount = Number(req.body.amount || 0);
    if (!Number.isFinite(amount) || amount <= 0) return res.status(400).json({ error: "Valid collection amount is required" });
    const bill = await WarehouseRentBill.findById(req.params.id);
    if (!bill) return res.status(404).json({ error: "Rent bill not found" });
    if (bill.status === "cancelled") return res.status(400).json({ error: "Cancelled bill cannot be collected" });
    const currentBalance = Math.max(Number(bill.total_amount || 0) - Number(bill.collected_amount || 0), 0);
    if (amount > currentBalance + 0.0001) return res.status(400).json({ error: `Collection amount cannot exceed balance ${currentBalance.toFixed(2)}` });
    bill.collected_amount = Number((Number(bill.collected_amount || 0) + amount).toFixed(2));
    bill.balance_amount = Number((Number(bill.total_amount || 0) - bill.collected_amount).toFixed(2));
    bill.collection_date = String(req.body.collection_date || istToday());
    bill.collection_mode = String(req.body.collection_mode || "");
    bill.reference_no = String(req.body.reference_no || "");
    bill.remarks = String(req.body.remarks || bill.remarks || "");
    bill.status = bill.balance_amount <= 0.0001 ? "collected" : "partial";
    await bill.save();

    const bookingStatus = bill.status === "collected" ? "paid" : "partial";
    const companyBookings = bill.items.map((item) => String(item.booking_id));
    if (companyBookings.length) {
      // Allocation is proportional to remaining booking balances. This keeps the
      // bill and its component bookings aligned without changing old voucher flows.
      let remainingCollection = amount;
      const bookings = await WarehouseRentBooking.find({ _id: { $in: companyBookings } }).sort({ createdAt: 1 });
      for (const booking of bookings) {
        if (remainingCollection <= 0) break;
        const bookingBalance = Math.max(Number(booking.monthly_rent || 0) - Number(booking.paid_amount || 0), 0);
        const allocated = Math.min(bookingBalance, remainingCollection);
        if (allocated <= 0) continue;
        booking.paid_amount = Number((Number(booking.paid_amount || 0) + allocated).toFixed(2));
        booking.balance_amount = Number((Number(booking.monthly_rent || 0) - booking.paid_amount).toFixed(2));
        booking.status = booking.balance_amount <= 0.0001 ? "paid" : "partial";
        await booking.save();
        remainingCollection -= allocated;
      }
      if (bill.status === "collected") {
        await WarehouseRentBooking.updateMany({ _id: { $in: companyBookings } }, { $set: { status: bookingStatus, balance_amount: 0 } });
      }
    }
    return res.json({ ok: true, bill: { ...bill.toObject(), id: String(bill._id) } });
  } catch (error) {
    console.error(error);
    return res.status(500).json({ error: error.message });
  }
});

router.get("/workflow", async (req, res) => {
  try {
    if (!canReport(req)) return res.status(403).json({ error: "Permission denied" });
    const filter = {};
    if (req.query.rent_month) filter.rent_month = String(req.query.rent_month);
    if (req.query.company_id) filter.company_id = req.query.company_id;
    const bookings = await WarehouseRentBooking.find(filter)
      .populate("warehouse_id", "name rent_flow")
      .populate("company_id", "name")
      .sort({ rent_month: -1, company_id: 1, createdAt: 1 });
    const billMap = new Map();
    const bills = await WarehouseRentBill.find(filter).lean();
    bills.forEach((bill) => billMap.set(`${String(bill.company_id)}::${bill.rent_month}`, bill));
    const rows = bookings.map((booking) => {
      const bill = booking.bill_id ? billMap.get(`${String(booking.company_id)}::${booking.rent_month}`) : null;
      return {
        id: String(booking._id),
        rent_month: booking.rent_month,
        warehouse_id: booking.warehouse_id?._id ? String(booking.warehouse_id._id) : String(booking.warehouse_id || ""),
        warehouse_name: booking.warehouse_id?.name || "",
        company_id: booking.company_id?._id ? String(booking.company_id._id) : String(booking.company_id || ""),
        company_name: booking.company_id?.name || "",
        rent_flow: booking.rent_flow || booking.warehouse_id?.rent_flow || "payable",
        booking_no: booking.booking_no,
        booking_status: booking.status,
        booking_amount: Number(booking.monthly_rent || 0),
        bill_no: bill?.bill_no || "",
        bill_status: bill?.status || "",
        bill_amount: Number(bill?.total_amount || 0),
        collected_amount: Number(bill?.collected_amount || 0),
        balance_amount: Number(bill?.balance_amount || 0),
      };
    });
    const summary = new Map();
    for (const row of rows) {
      const key = `${row.rent_month}::${row.company_id || row.warehouse_id}`;
      if (!summary.has(key)) summary.set(key, { rent_month: row.rent_month, company_name: row.company_name, rent_flow: row.rent_flow, warehouses: 0, booking_amount: 0, bill_no: row.bill_no, bill_status: row.bill_status, bill_amount: row.bill_amount, collected_amount: row.collected_amount, balance_amount: row.balance_amount });
      const item = summary.get(key);
      item.warehouses += 1;
      item.booking_amount += row.booking_amount;
    }
    return res.json({ summary: [...summary.values()], details: rows });
  } catch (error) {
    console.error(error);
    return res.status(500).json({ error: error.message });
  }
});

router.get("/:id", async (req, res) => {
  try {
    if (!canReport(req)) return res.status(403).json({ error: "Permission denied" });
    const bill = await WarehouseRentBill.findById(req.params.id).populate("company_id", "name address mobile gst_no pan_no").populate("items.warehouse_id", "name");
    if (!bill) return res.status(404).json({ error: "Rent bill not found" });
    return res.json({ ...bill.toObject(), id: String(bill._id), company_name: bill.company_id?.name || "" });
  } catch (error) {
    console.error(error);
    return res.status(500).json({ error: error.message });
  }
});

module.exports = router;
module.exports.runWarehouseRentAutoClose = runWarehouseRentAutoClose;
